name 'fenton_integration_test'
maintainer 'Fenton Project'
maintainer_email 'nickwillever@gmail.com'
license 'apache2'
description 'Installs/Configures fenton_integration_test'
long_description 'Installs/Configures fenton_integration_test'
version '0.1.0'
